### ISSUE TITLE
Unable to import generated files

### ISSUE THREAD

**Issue by s-kostyuk** [fritzing/eagle2fritzing#5]
Both tools from the repo produces files which Frizting (v0.9.2) doesn't recognise on import. Fritzing import tool doesn't see `.fzp` files at all and returns `unable to find following part` while import of bin.

See illustration here: https://youtu.be/AFkjHF8NNZA
Grab files here: https://app.box.com/e2f-issue-4

**Comment by el-j** [comment]
the output of the tool is not a fritzing parts-file. (fzpz) what you get is a bin file for fritzing together with the extracted 4 files to fit in the fritzing-folder-structure. the failure you see, means simply that fritzing is looking in the false directory to find the fzp.

so, put your files to:
fritzing/parts/svg/core --> the svgs
fritzing/parts/core --> fzp file
fritizng/bins -> the fzb

reload fritzing, and you should see your bin and the parts inside. you could also put the files in the "user" or "contrib" structure. that makes it easier to hold the core-parts clean.

for a better use there should be an option to decide, if you want a fritzing-part (fzpz) or an "open file" output.

**Comment by aknoerig** [comment]
The issue here is that the files that are generated are not meant to be imported via the GUI. Instead, you need to copy the generated files into either the program's file structure or your user data folder.
You can then also create a shareable fzpz file out of it from within Fritzing (via Part > Export).

However, your use case should be standard and so I just created an issue request for this. We basically need to hook up the fzpz export command (which is part of fritzing-app) to this script.

Here's the proof that it works  :)
![bildschirmfoto 2015-08-12 um 12 34 12](https://cloud.githubusercontent.com/assets/481350/9221971/7912e208-40ee-11e5-8e2a-dfd102ca8bcc.png)

**Comment by aknoerig** [comment]
Oh wow, now you're getting help from two sides simultaneously. :)

**Comment by s-kostyuk** [comment]
Oh, many thanks :)
